import reflex as rx

from vet_tech.features.auth.state import State


def login_view() -> rx.Component:
    formulario = rx.form(
        rx.vstack(
            rx.input(
                placeholder="E-mail ou CPF",
                type="email",
                name="email",
                required=True,
                width="100%",
                height="44px",
                padding_x="14px",
                background="#EEF0F2",
                border="1px solid transparent",
                border_radius="14px",
                color="#1A3629",
                font_family="Nunito",
                font_size="14px",
                _focus={"border": "1.5px solid #689554", "box_shadow": "none"},
            ),
            rx.input(
                placeholder="Senha",
                type="password",
                name="password",
                required=True,
                width="100%",
                height="44px",
                padding_x="14px",
                background="#EEF0F2",
                border="1px solid transparent",
                border_radius="14px",
                color="#1A3629",
                font_family="Nunito",
                font_size="14px",
                _focus={"border": "1.5px solid #689554", "box_shadow": "none"},
            ),
            rx.hstack(
                rx.hstack(
                    rx.box(
                        rx.text("✓", color="white", font_size="12px"),
                        width="17px",
                        height="17px",
                        display="flex",
                        align_items="center",
                        justify_content="center",
                        background="#689554",
                        border_radius="3px",
                    ),
                    rx.text(
                        "Lembrar de mim?",
                        color="#222222",
                        font_family="Nunito",
                        font_size="13px",
                    ),
                    align="center",
                    spacing="2",
                ),
                rx.text(
                    "Esqueceu a senha?",
                    color="#689554",
                    font_family="Nunito",
                    font_size="13px",
                    white_space="nowrap",
                ),
                width="100%",
                align="center",
                justify="between",
            ),
            rx.button(
                rx.cond(State.is_busy, "Entrando...", "Login"),
                type="submit",
                disabled=State.is_busy,
                width="100%",
                height="36px",
                padding="0",
                background="#689554",
                color="white",
                border="none",
                border_radius="999px",
                font_family="Nunito",
                font_size="14px",
                font_weight="600",
                cursor="pointer",
                _hover={"background": "#5D874A"},
            ),
            rx.text(
                State.login_message,
                role="status",
                width="100%",
                min_height="18px",
                color="#A33232",
                font_family="Nunito",
                font_size="13px",
                text_align="center",
            ),
            align="stretch",
            spacing="3",
            width="100%",
        ),
        on_submit=State.login,
        width="min(100%, 312px)",
    )

    painel_formulario = rx.vstack(
        rx.image(
            src="/mascote_logo.png",
            alt="Mascote Vet Tech",
            width="80px",
            height="80px",
            object_fit="contain",
        ),
        rx.heading(
            "Vet Tech",
            as_="h1",
            font_family="Nunito",
            font_size="32px",
            font_weight="400",
            line_height="1",
            color="#1A3629",
        ),
        rx.vstack(
            rx.text(
                "Bem-Vindo de Volta!",
                color="#111111",
                font_family="Nunito",
                font_size="22px",
                font_weight="700",
                line_height="1.2",
            ),
            rx.text(
                "Acesse sua conta para cuidar do seu melhor amigo.",
                color="#222222",
                font_family="Nunito",
                font_size="18px",
                line_height="1.3",
                text_align="center",
            ),
            align="center",
            spacing="1",
            width="100%",
        ),
        formulario,
        rx.hstack(
            rx.box(height="1px", flex="1", background="#D9DDE0"),
            rx.text(
                "ou",
                color="#8A8F98",
                font_family="Nunito",
                font_size="11px",
            ),
            rx.box(height="1px", flex="1", background="#D9DDE0"),
            width="100%",
            align="center",
            spacing="2",
        ),
        rx.hstack(
            rx.image(
                src="https://www.gstatic.com/firebasejs/ui/2.0.0/images/auth/google.svg",
                alt="",
                width="18px",
                height="18px",
            ),
            rx.text("Entrar com Google", font_family="Nunito", font_size="14px"),
            width="100%",
            height="36px",
            align="center",
            justify="center",
            spacing="2",
            background="white",
            color="#111111",
            border="1px solid #777777",
            border_radius="999px",
            cursor="default",
        ),
        rx.button(
            rx.hstack(
                rx.text(
                    "Não tem uma conta?",
                    color="#222222",
                    font_family="Nunito",
                    font_size="13px",
                ),
                rx.text(
                    "Cadastre-se!",
                    color="#689554",
                    font_family="Nunito",
                    font_size="13px",
                ),
                spacing="1",
                justify="center",
                width="100%",
            ),
            on_click=State.show_signup,
            variant="ghost",
            padding="0",
            height="auto",
            cursor="pointer",
        ),
        width="min(100%, 440px)",
        max_width="100%",
        align="center",
        justify="center",
        spacing="3",
    )

    return rx.box(
        rx.box(
            rx.hstack(
                rx.box(
                    painel_formulario,
                    width=["100%", "100%", "52%"],
                    height="100%",
                    padding=["28px 22px", "36px 30px", "32px 48px"],
                    background="white",
                    display="flex",
                    align_items="center",
                    justify_content="center",
                ),
                rx.box(
                    width="48%",
                    height="100%",
                    background="#72935B",
                    background_image="url('/fundo02.jpeg')",
                    background_size="cover",
                    background_position="center",
                    background_repeat="no-repeat",
                    display=["none", "none", "block"],
                ),
                width="100%",
                height="100%",
                flex_direction=["column", "column", "row"],
                overflow="hidden",
                border_radius="32px",
            ),
            display="flex",
            align_items=["flex-start", "center"],
            justify_content="center",
            width="min(1040px, 100%)",
            height=["auto", "auto", "min(92vh, 708px)"],
            min_height=["auto", "auto", "560px"],
            overflow="hidden",
            border_radius=["20px", "28px", "32px"],
            background="white",
            box_shadow="0 22px 65px rgba(20, 39, 24, 0.24)",
        ),
        min_height="100vh",
        width="100%",
        display="flex",
        align_items=["flex-start", "center"],
        justify_content="center",
        padding=["14px", "18px"],
        background="#1C1C1E",
    )


def signup_view() -> rx.Component:
    return rx.container(
        rx.vstack(
            rx.heading("Cadastro de tutor", size="6"),
            rx.text("Preencha seus dados para criar sua conta."),
            rx.form(
                rx.vstack(
                    rx.input(
                        placeholder="Nome completo",
                        type="text",
                        name="nome",
                        required=True,
                        width="100%",
                    ),
                    rx.input(
                        placeholder="CPF",
                        type="text",
                        name="cpf",
                        value=State.signup_cpf,
                        on_change=State.set_signup_cpf,
                        required=True,
                        max_length=14,
                        width="100%",
                    ),
                    rx.text(State.signup_cpf_feedback, role="status"),
                    rx.input(
                        placeholder="E-mail",
                        type="email",
                        name="email",
                        required=True,
                        width="100%",
                    ),
                    rx.input(
                        placeholder="Telefone",
                        type="tel",
                        name="telefone",
                        required=True,
                        width="100%",
                    ),
                    rx.input(
                        placeholder="Endereço",
                        type="text",
                        name="endereco",
                        required=True,
                        width="100%",
                    ),
                    rx.input(
                        placeholder="Senha",
                        type="password",
                        name="password",
                        required=True,
                        width="100%",
                    ),
                    rx.button(
                        "Cadastrar",
                        type="submit",
                        disabled=State.is_busy,
                        width="100%",
                    ),
                    align="stretch",
                    spacing="3",
                    width="100%",
                ),
                on_submit=State.signup,
                width="100%",
            ),
            rx.text(State.signup_message, role="status"),
            rx.button(
                "Já tenho uma conta",
                on_click=State.show_login,
                variant="ghost",
            ),
            spacing="3",
            align="stretch",
            width="100%",
            max_width="32rem",
        ),
        padding_top="4rem",
    )
